### ISSUE TITLE
Page controls sometimes scroll off the top of the screen and we can't get to them.

### ISSUE THREAD

**Issue by maboa** [hyperaudio/ha-converter#1]
Some CSS issue I think.

**Comment by circuitbomb** [comment]
I'm experiencing the same issue locally, removing the overflow:hidden property brings the Iframe content back down but adds scroll-bars.

**Comment by Laurian** [comment]
check what is 100% height and it shouldn't be so

**Comment by maboa** [comment]
I fixed this to the extent we now have scroll bars - I removed overflow:
hidden; from #wrapper in styles.css. The organisation of CSS/JS is a bit of
a mess, I should tidy.

## 

_Mark Boas_
happyworm.com | jPlayer.org http://jplayer.org/
skype: mark_boas
follow: @maboa @jplayerorg
