### ISSUE TITLE
Google STT converter

### ISSUE THREAD

**Issue by overZellis133** [hyperaudio/ha-converter#8]
www.theirstory.io is a web-based interviewing & storytelling platform to help facilitate, record, transcribe, index, digitally archive, and share meaningful stories and conversations. Today, TheirStory allows users to generate a transcript of an audiovisual recording by using Google's STT services. That transcript gets added to a Word Document, which the user can download.

We would like to be able to translate the data generated by Google STT, and in addition to generating a Word Document, pipe the Google STT data into Hyperaudio Lite. We would then look to integrate Hyperaudio Lite into TheirStory so that we can allow users to generate their own interactive transcripts associated with their audiovisual records within TheirStory.

@maboa is this something you can help with?

**Comment by maboa** [comment]
@overZellis133 Yes - I can :) Do you have a couple of examples of the JSON that Google's STT generates?

**Comment by overZellis133** [comment]
@maboa Yes, I will get this to you soon.

**Comment by overZellis133** [comment]
@maboa is there a way to upload JSON file here? I've attached the JSON in a Word doc, but I feel as though there has to be a better way to share this with you...
[BethEl_TheirStory_Interview_JSON.docx](https://github.com/hyperaudio/ha-converter/files/3928523/BethEl_TheirStory_Interview_JSON.docx)

**Comment by overZellis133** [comment]
@maboa, happy to provide a JSON file for other transcripts if that would be helpful. Just let me know.

**Comment by maboa** [comment]
@overZellis133 I downloaded the JSON - but there seems to be an issue with the formatting. As the keys are not wrapped with double quotes as is usually the case https://stackoverflow.com/questions/949449/do-the-json-keys-have-to-be-surrounded-by-quotes

Not sure if they got stripped out somewhere in the process?

**Comment by overZellis133** [comment]
[theirstory_transcript.docx](https://github.com/hyperaudio/ha-converter/files/4099781/theirstory_transcript.docx)
@maboa I uploaded a new file where the keys are in quotes

I was originally using JSONview as a Chrome extension, which stripped out the quotes.

**Comment by maboa** [comment]
OK @

**Comment by maboa** [comment]
OK @overZellis133  I have added an option for Google STT JSON conversion now, at least it appears to work with the test data you supplied. It does not as yet split into paragraphs based on time elapsed between words. It would make sense to open that request as a separate issue though.

**Comment by overZellis133** [comment]
Awesome. Thanks @maboa. I just filed the new issue.
